### PR TITLE
Configurable broker port

### PR DESCRIPTION
**Pull request by DayoOliyide**
There's a few times I've needed to run the broker on other ports.
Shouldn't break anything existing.

--Dayo

### CODE REVIEW

**Comment by BrunoBonacci** [comment]
The internal port is irrelevant, is the mapping which decide which port gets exposed in the outside
for example
```
docker run -p 8082:9092 samsara/kafka
```

what's the case that you couldn't handle?

**Comment by DayoOliyide** [comment]
I was looking into connecting to a multi-broker cluster that was inside
a VM (boot2docker, docker-machine) and had some networking issues where
the port reported by the brokers, via meta-data, wasn't reachable.

I found a solution but in investigating and playing around I found it useful to be able to change the advertised port by just changing/adding an env variable in the docker-compose.yml. Hence the first commit, the second commit is
debateable and can be dismissed.

In most cases, this won't be needed, but it's nice to have.

**Comment by BrunoBonacci** [comment]
I know this scenario. 
In Kafka there are two cfg parameter expressively for this:

advertised.host.name	null	
If this is set this is the hostname that will be given out to producers, consumers, and other brokers to connect to.

advertised.port	null	
The port to give out to producers, consumers, and other brokers to use in establishing connections. This only needs to be set if this port is different from the port the server should bind to.


Check
http://kafka.apache.org/081/configuration.html

**Comment by BrunoBonacci** [comment]
merged, rebuilt image, and pushed as: `samsara/kafka:0.8.2.1c`

**Pull request merged**
